name: run pytest

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      
      - name: Run pytest
        run: |
          python -m pytest --junit-xml results/pytest.xml
        continue-on-error: true

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: test_results
          path: results/*.xml

      - name: Download results
        uses: actions/download-artifact@v3
        with:
          name: test_results
          path: artifacts

      - name: display results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: artifacts/**/*.xml
